version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12.9.1-browsers
    steps:
      - checkout
      - run: npm install
      - run: npm run build
  test:
    docker:
      - image: circleci/node:12.9.1-browsers
    steps:
      - checkout
      - run: npm install
      - run: npm run test
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test